# PAGE INFORMATION
LOGIN_PAGE = 0
PATIENT_SELECTION = 1
PATIENT_LOADING = 2
CHAT_INTERFACE = 3
POST_INTERVIEW = 4
PHYSICAL_SCREEN = 5
ECG_SCREEN = 6
FEEDBACK_SCREEN = 7
FINAL_SCREEN = 8

# GPT
MODEL = "gpt-4"

# EMAIL API
EMAIL_TO_SEND = [('rutgers.aime@gmail.com')]