# PAGE INFORMATION
LOGIN_PAGE = 0
SETTINGS = 1
CHAT_SETUP = 2
CHAT_INTERFACE_TEXT = 3
CHAT_INTERFACE_VOICE = 4
POST_INTERVIEW = 5
PHYSICAL_SCREEN = 6
ECG_SCREEN = 7
FEEDBACK_SETUP = 8
FEEDBACK_SCREEN = 9
FINAL_SCREEN = 10

# GPT
MODEL = "gpt-4"

# EMAIL API
EMAIL_TO_SEND = [('rutgers.aime@gmail.com')]

# Classification related
CLASSIFY_GEN_PROMPT = "./Prompts/Class_gen_2-7.txt"
CLASSIFY_DIMS_PROMPT = "./Prompts/Class_dims_2-8.txt"